wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1713359923.0
    t:
      1:
      - 1
      - 4
      - 5
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
